server:
  port: 9276
  servlet:
    session:
      timeout: PT8H
spring:
  datasource:
#    url: jdbc:mysql/useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
#    username:
#    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 10
    max-idle: 5
    min-idle: 1
    initial-size: 1
    max-wait: 6000
    validation-query: select 1
    test-while-idle: true
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 600000
  redis:
    database: 0
    host: 106.55.48.201
    port: 7379
    password: 2020test
    timeout: 10000