# mysql
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  type-aliases-package: com.qr.anti.po